const DAYS_AR=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const MONTHS_AR=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
const uid=()=>Math.random().toString(36).slice(2,9);
const defaultState={
  month:'2026-09',activeWeek:0,
  rules:{minA:1,minB:1,maxConsecutive:6,sixthAllowed:true,weekStart:0},
  employees:[
    {id:uid(),name:'بلال',mode:'ROTATE',startShift:'B',off1:5,off2:6,priorStreak:0},
    {id:uid(),name:'الشخص 2',mode:'ROTATE',startShift:'A',off1:0,off2:1,priorStreak:0},
    {id:uid(),name:'الشخص 3',mode:'ROTATE',startShift:'B',off1:2,off2:3,priorStreak:0},
    {id:uid(),name:'الشخص 4',mode:'FIXED_A',startShift:'A',off1:4,off2:5,priorStreak:0}
  ],overrides:{},notes:{}
};
let state=loadState();let schedule=[];let selectedCell=null;let installPrompt=null;
function loadState(){try{const s=JSON.parse(localStorage.getItem('qwh_state'));return s?{...defaultState,...s,rules:{...defaultState.rules,...s.rules}}:structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem('qwh_state',JSON.stringify(state));toast('تم حفظ البيانات')}
function dateKey(d){return d.toISOString().slice(0,10)}
function monthDateParts(){const [y,m]=state.month.split('-').map(Number);return {y,m}}
function daysInMonth(){const {y,m}=monthDateParts();return new Date(y,m,0).getDate()}
function makeDates(){const {y,m}=monthDateParts();return Array.from({length:daysInMonth()},(_,i)=>new Date(y,m-1,i+1,12))}
function weekIndexFor(d){const first=new Date(d.getFullYear(),d.getMonth(),1,12);const offset=(first.getDay()-state.rules.weekStart+7)%7;return Math.floor((offset+d.getDate()-1)/7)}
function baseAssignment(emp,d){if(d.getDay()===Number(emp.off1)||d.getDay()===Number(emp.off2))return 'OFF';if(emp.mode==='FIXED_A')return 'A';if(emp.mode==='FIXED_B')return 'B';const parity=weekIndexFor(d)%2;const start=emp.startShift||'A';return parity===0?start:(start==='A'?'B':'A')}
function getAssignment(emp,d){return state.overrides[`${emp.id}|${dateKey(d)}`]||baseAssignment(emp,d)}
function buildSchedule(){schedule=makeDates().map(d=>({date:d,assignments:Object.fromEntries(state.employees.map(e=>[e.id,getAssignment(e,d)]))}));renderAll()}
function calcStreaks(){const result={};for(const e of state.employees){let streak=Number(e.priorStreak||0);result[e.id]={};for(const day of schedule){const a=day.assignments[e.id];if(a==='OFF')streak=0;else streak++;result[e.id][dateKey(day.date)]=streak}}return result}
function coverage(day){let A=0,B=0;Object.values(day.assignments).forEach(v=>{if(v==='A')A++;if(v==='B')B++});return {A,B}}
function analyze(){const streaks=calcStreaks();const issues=[];let sixth=0,critical=0,coverageBad=0;for(const day of schedule){const cov=coverage(day);const key=dateKey(day.date);if(cov.A<state.rules.minA){coverageBad++;critical++;issues.push({id:`covA-${key}`,type:'coverage',level:'critical',date:day.date,missing:'A',title:`لا يوجد تغطية كافية لشفت A`,desc:`التغطية الحالية A=${cov.A} بينما الحد الأدنى ${state.rules.minA}.`})}if(cov.B<state.rules.minB){coverageBad++;critical++;issues.push({id:`covB-${key}`,type:'coverage',level:'critical',date:day.date,missing:'B',title:`لا يوجد تغطية كافية لشفت B`,desc:`التغطية الحالية B=${cov.B} بينما الحد الأدنى ${state.rules.minB}.`})}for(const e of state.employees){const st=streaks[e.id][key];if(st===6){sixth++;issues.push({id:`six-${e.id}-${key}`,type:'sixth',level:'warning',date:day.date,emp:e,title:`${e.name} داخل يومه السادس`,desc:'اليوم السادس مسموح، لكن التطبيق يوضحه حتى تختار إبقاءه أو إعطاءه راحة.'})}if(st>=7){critical++;issues.push({id:`sev-${e.id}-${key}`,type:'seventh',level:'critical',date:day.date,emp:e,title:`${e.name} وصل لليوم السابع — ممنوع`,desc:'لازم ينفصل بيوم عطلة قبل الاستمرار. اختر أحد الحلول المقترحة أدناه.'})}}}
return {issues,streaks,sixth,critical,coverageBad}}
function solutionsFor(issue,analysis){const day=schedule.find(x=>dateKey(x.date)===dateKey(issue.date));if(!day)return[];const out=[];if(issue.type==='coverage'){
  const target=issue.missing,opp=target==='A'?'B':'A';
  state.employees.filter(e=>day.assignments[e.id]===opp && !(e.mode===`FIXED_${opp}`)).forEach(e=>out.push({label:`حوّل ${e.name} إلى ${target}`,act:()=>setOverride(e.id,issue.date,target,`تغطية شفت ${target}`)}));
  state.employees.filter(e=>day.assignments[e.id]==='OFF').forEach(e=>out.push({label:`شغّل ${e.name} ${target} بدل عطلته`,act:()=>setOverride(e.id,issue.date,target,`تغطية طارئة لشفت ${target} - يحتاج تعويض عطلة`)}));
}
if(issue.type==='sixth'){
  out.push({label:'يبقى مداوم يوم سادس',act:()=>toast('تم الإبقاء على اليوم السادس كما هو')});
  out.push({label:`عطّل ${issue.emp.name} اليوم`,act:()=>setOverride(issue.emp.id,issue.date,'OFF','راحة في اليوم السادس')});
}
if(issue.type==='seventh'){
  out.push({label:`عطّل ${issue.emp.name} اليوم`,act:()=>setOverride(issue.emp.id,issue.date,'OFF','فصل اليوم السابع الممنوع')});
  const prev=new Date(issue.date);prev.setDate(prev.getDate()-1);if(prev.getMonth()===issue.date.getMonth())out.push({label:'خليه يعطل اليوم السابق',act:()=>setOverride(issue.emp.id,prev,'OFF','فصل قبل اليوم السابع')});
  const needed=day.assignments[issue.emp.id];state.employees.filter(e=>e.id!==issue.emp.id && day.assignments[e.id]==='OFF').forEach(e=>out.push({label:`${e.name} يداوم ${needed} ويعوض عطلته`,act:()=>{setOverride(issue.emp.id,issue.date,'OFF','فصل اليوم السابع');setOverride(e.id,issue.date,needed,'تغطية بدل موظف يفصل يوم سابع - يحتاج تعويض عطلة',false);buildSchedule();toast('تم تطبيق الحل، راجع تنبيهات التعويض')}}));
}
return out.slice(0,6)}
function setOverride(empId,d,val,note='',rebuild=true){state.overrides[`${empId}|${dateKey(d)}`]=val;if(note)state.notes[`${empId}|${dateKey(d)}`]=note;if(rebuild)buildSchedule()}
function renderAll(){renderMonthInfo();renderWeekTabs();renderSchedule();renderIssues();renderTeam();renderRules()}
function renderMonthInfo(){const {y,m}=monthDateParts();document.getElementById('monthLabel').textContent=`${MONTHS_AR[m-1]} ${y}`;document.getElementById('sumMonth').textContent=MONTHS_AR[m-1];const a=analyze();document.getElementById('sumCritical').textContent=a.critical;document.getElementById('sumSixth').textContent=a.sixth;document.getElementById('sumCoverage').textContent=a.coverageBad?'تحتاج تعديل':'ممتازة';document.getElementById('sumCoverage').style.color=a.coverageBad?'var(--red)':'var(--green)'}
function weeks(){const groups=[];for(const d of schedule){const wi=weekIndexFor(d.date);groups[wi]??=[];groups[wi].push(d)}return groups.filter(Boolean)}
function renderWeekTabs(){const root=document.getElementById('weekTabs');const ws=weeks();if(state.activeWeek>=ws.length)state.activeWeek=ws.length-1;root.innerHTML=ws.map((w,i)=>`<button class="week-tab ${i===state.activeWeek?'active':''}" data-week="${i}">الأسبوع ${i+1} · ${w[0].date.getDate()}–${w[w.length-1].date.getDate()}</button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.activeWeek=Number(b.dataset.week);renderWeekTabs();renderSchedule()})}
function renderSchedule(){const root=document.getElementById('scheduleWrap');const ws=weeks();const w=ws[state.activeWeek]||[];if(!w.length){root.innerHTML='<div class="empty-state">لا يوجد أيام</div>';return}const analysis=analyze();let html='<div class="schedule-scroll"><table class="schedule-table"><thead><tr><th>الاسم</th>'+w.map(x=>`<th><div class="day-head"><strong>${DAYS_AR[x.date.getDay()]}</strong><span>${x.date.getDate()}/${x.date.getMonth()+1}</span></div></th>`).join('')+'</tr></thead><tbody>';
for(const e of state.employees){html+=`<tr><td><span class="emp-name">${esc(e.name)}</span><span class="emp-type">${e.mode==='ROTATE'?'يتقلب A/B':e.mode==='FIXED_A'?'ثابت A':'ثابت B'}</span></td>`;for(const day of w){const key=dateKey(day.date),a=day.assignments[e.id],st=analysis.streaks[e.id][key],cov=coverage(day);const cls=[a.toLowerCase(),st===6?'sixth':'',st>=7?'seventh':'',(a==='A'&&cov.A<state.rules.minA)||(a==='B'&&cov.B<state.rules.minB)?'coverage':''].join(' ');const flag=st>=7?'7!':st===6?'6':'';html+=`<td><button class="cell-btn ${cls}" data-emp="${e.id}" data-date="${key}">${flag?`<span class="mini-flag">${flag}</span>`:''}${a==='OFF'?'عطلة':a}</button></td>`}html+='</tr>'}
html+='<tr class="coverage-row"><td>التغطية</td>'+w.map(day=>{const c=coverage(day);return `<td><span class="coverage-pill ${c.A<state.rules.minA?'bad':''}">A ${c.A}</span><span class="coverage-pill ${c.B<state.rules.minB?'bad':''}">B ${c.B}</span></td>`}).join('')+'</tr></tbody></table></div>';root.innerHTML=html;root.querySelectorAll('.cell-btn').forEach(b=>b.onclick=()=>openEdit(b.dataset.emp,b.dataset.date))}
function renderIssues(){const root=document.getElementById('issuesList');const a=analyze();if(!a.issues.length){root.innerHTML='<div class="empty-state">✓ الجدول سليم: لا يوم سابع ولا نقص تغطية.</div>';return}root.innerHTML=a.issues.map((it,i)=>{const sols=solutionsFor(it,a);return `<div class="issue ${it.level}"><div class="issue-head"><h3>${esc(it.title)}</h3><span class="badge">${fmtDate(it.date)}</span></div><p>${esc(it.desc)}</p><div class="solutions">${sols.map((s,j)=>`<button class="solution-btn" data-i="${i}" data-j="${j}">${esc(s.label)}</button>`).join('')}</div></div>`}).join('');root.querySelectorAll('.solution-btn').forEach(btn=>btn.onclick=()=>{const i=+btn.dataset.i,j=+btn.dataset.j;const current=analyze();const sol=solutionsFor(current.issues[i],current)[j];if(sol)sol.act()})}
function renderTeam(){const root=document.getElementById('teamCards');root.innerHTML=state.employees.map((e,i)=>`<div class="team-card" data-id="${e.id}"><div class="team-top"><div class="avatar">${i+1}</div><div style="flex:1"><input class="name-input" value="${escAttr(e.name)}" style="width:100%;border:0;border-bottom:1px solid var(--line);font-size:16px;font-weight:900;color:var(--navy);padding:7px 2px"></div></div><div class="field-grid"><label>نظام الشفت<select class="mode"><option value="ROTATE" ${e.mode==='ROTATE'?'selected':''}>يتقلب A / B</option><option value="FIXED_A" ${e.mode==='FIXED_A'?'selected':''}>ثابت A</option><option value="FIXED_B" ${e.mode==='FIXED_B'?'selected':''}>ثابت B</option></select></label><label>بداية الشهر<select class="start"><option value="A" ${e.startShift==='A'?'selected':''}>A</option><option value="B" ${e.startShift==='B'?'selected':''}>B</option></select></label><label>العطلة الأولى<select class="off1">${dayOptions(e.off1)}</select></label><label>العطلة الثانية<select class="off2">${dayOptions(e.off2)}</select></label><label>أيام متتالية قبل بداية الشهر<input class="prior" type="number" min="0" max="6" value="${e.priorStreak||0}"></label></div></div>`).join('');root.querySelectorAll('.team-card').forEach(card=>{const e=state.employees.find(x=>x.id===card.dataset.id);card.querySelector('.name-input').onchange=ev=>{e.name=ev.target.value||'بدون اسم';buildSchedule()};card.querySelector('.mode').onchange=ev=>{e.mode=ev.target.value;buildSchedule()};card.querySelector('.start').onchange=ev=>{e.startShift=ev.target.value;buildSchedule()};card.querySelector('.off1').onchange=ev=>{e.off1=+ev.target.value;buildSchedule()};card.querySelector('.off2').onchange=ev=>{e.off2=+ev.target.value;buildSchedule()};card.querySelector('.prior').onchange=ev=>{e.priorStreak=+ev.target.value;buildSchedule()}})}
function dayOptions(sel){return DAYS_AR.map((d,i)=>`<option value="${i}" ${i===Number(sel)?'selected':''}>${d}</option>`).join('')}
function renderRules(){minA.value=state.rules.minA;minB.value=state.rules.minB;maxConsecutive.value=state.rules.maxConsecutive;sixthAllowed.checked=state.rules.sixthAllowed;weekStart.value=state.rules.weekStart}
function openEdit(empId,key){const e=state.employees.find(x=>x.id===empId);const d=new Date(key+'T12:00:00');selectedCell={empId,key,d};editTitle.textContent=`تعديل ${e.name}`;editSubtitle.textContent=`${DAYS_AR[d.getDay()]} ${fmtDate(d)} · الحالي ${getAssignment(e,d)==='OFF'?'عطلة':getAssignment(e,d)}`;overrideNote.value=state.notes[`${empId}|${key}`]||'';editModal.classList.remove('hidden')}
function closeEdit(){editModal.classList.add('hidden');selectedCell=null}
function autoSolve(){let changed=0;for(let pass=0;pass<12;pass++){
  const a=analyze();let did=false;
  const severe=a.issues.find(i=>i.type==='seventh');if(severe){const day=schedule.find(x=>dateKey(x.date)===dateKey(severe.date));const ass=day.assignments[severe.emp.id];const cov=coverage(day);const canRest=(ass==='A'?cov.A>state.rules.minA:cov.B>state.rules.minB);if(canRest){setOverride(severe.emp.id,severe.date,'OFF','حل تلقائي: فصل اليوم السابع',false);did=true;changed++}else{const offEmp=state.employees.find(e=>e.id!==severe.emp.id&&day.assignments[e.id]==='OFF'&&((a.streaks[e.id][dateKey(severe.date)]||0)<6));if(offEmp){setOverride(severe.emp.id,severe.date,'OFF','حل تلقائي: فصل اليوم السابع',false);setOverride(offEmp.id,severe.date,ass,'حل تلقائي: تغطية مع ضرورة تعويض عطلة',false);did=true;changed++}}}
  if(!did){const covIssue=a.issues.find(i=>i.type==='coverage');if(covIssue){const day=schedule.find(x=>dateKey(x.date)===dateKey(covIssue.date));const target=covIssue.missing,opp=target==='A'?'B':'A';const cand=state.employees.find(e=>day.assignments[e.id]===opp && e.mode==='ROTATE');if(cand){setOverride(cand.id,covIssue.date,target,'حل تلقائي: تصحيح تغطية',false);did=true;changed++}else{const off=state.employees.find(e=>day.assignments[e.id]==='OFF');if(off){setOverride(off.id,covIssue.date,target,'حل تلقائي: تغطية بدل عطلة - يحتاج تعويض',false);did=true;changed++}}}}
  if(!did)break;schedule=makeDates().map(d=>({date:d,assignments:Object.fromEntries(state.employees.map(e=>[e.id,getAssignment(e,d)]))}))
}
buildSchedule();const left=analyze().critical;toast(left?`طبقت ${changed} تعديلات، بقي ${left} تعارض يحتاج اختيار يدوي`:`تم الحل تلقائياً بدون مخالفات حرجة`)}
function changeMonth(delta){const {y,m}=monthDateParts();const d=new Date(y,m-1+delta,1);state.month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;state.activeWeek=0;buildSchedule()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`quality-working-hours-${state.month}.json`;a.click();URL.revokeObjectURL(a.href)}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.add('hidden'),2600)}
function fmtDate(d){return `${d.getDate()}/${d.getMonth()+1}/${d.getFullYear()}`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escAttr(s=''){return esc(s)}

document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(b.dataset.view).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})});
prevMonth.onclick=()=>changeMonth(-1);nextMonth.onclick=()=>changeMonth(1);saveBtn.onclick=saveState;regenerateBtn.onclick=()=>{state.overrides={};state.notes={};buildSchedule();toast('تم إنشاء جدول جديد حسب الإعدادات')};autoSolveBtn.onclick=autoSolve;
[minA,minB,maxConsecutive].forEach(el=>el.onchange=()=>{state.rules[el.id]=+el.value;buildSchedule()});sixthAllowed.onchange=()=>{state.rules.sixthAllowed=sixthAllowed.checked;buildSchedule()};weekStart.onchange=()=>{state.rules.weekStart=+weekStart.value;state.activeWeek=0;buildSchedule()};
closeModal.onclick=closeEdit;editModal.onclick=e=>{if(e.target===editModal)closeEdit()};document.querySelectorAll('[data-assignment]').forEach(b=>b.onclick=()=>{if(!selectedCell)return;setOverride(selectedCell.empId,selectedCell.d,b.dataset.assignment,overrideNote.value||'تعديل يدوي');closeEdit()});clearOverride.onclick=()=>{if(!selectedCell)return;delete state.overrides[`${selectedCell.empId}|${selectedCell.key}`];delete state.notes[`${selectedCell.empId}|${selectedCell.key}`];closeEdit();buildSchedule()};
exportBtn.onclick=exportData;importInput.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());state={...defaultState,...data,rules:{...defaultState.rules,...data.rules}};buildSchedule();saveState()}catch{toast('ملف النسخة الاحتياطية غير صالح')}};resetBtn.onclick=()=>{if(confirm('متأكد أنك تريد حذف كل البيانات؟')){state=structuredClone(defaultState);localStorage.removeItem('qwh_state');buildSchedule()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installBtn.style.display='block'});installBtn.onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else toast('على iPhone: مشاركة ← إضافة إلى الشاشة الرئيسية')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
buildSchedule();
